baseURL = 'https://platolytics.io/'
languageCode = 'en-us'
title = 'Platolytics'
theme = "spectral"

[params]
fancyTitle = "Platolytics" # title for frontpage, may include image
copyright = "Platolytics"
description = 'Your existing metrics available the way they make sense!'
startbuttonText = "Sign up!"
startbuttonLink = "#contact"
body_is_markdown = true

[params.one]
enable = true
title = 'Usable'
body = '''
The metrics you have already, ready to be read in a way you know.
'''

[[params.cta.link]]
href = "#contact"
text = "Learn More!"
special = false

[params.cta]
enable = false

[[params.menu.main]]
url = '/'
title = "Home"

[params.contact]
enable = true
title = "Signup!"
body = "Sign up to stay informed"
email = "nospam@example.com"
