baseURL = 'https://platolytics.io/'
languageCode = 'en-us'
title = 'Platolytics'
theme = "spectral"

[params]
#fancyTitle = '<img height="512" src="/images/logo-border.png" alt="Logo"/>'
fancyTitle = 'Platolytics'
#title for frontpage, may include image
copyright = "Platolytics"
description = 'Making your metrics available to your Analytics Team!'
startbuttonText = "Sign up!"
startbuttonLink = "#contact"
body_is_markdown = true

[params.one]
enable = true
title = 'Usable'
body = '''
The metrics you have already, ready to be read in a way your teams know.
'''

[params.two]
enable = true
[[params.two.section]]
title = 'Effective'
body = '''
Use all of your Prometheus metrics, not just a fraction.
'''
[[params.two.section]]
title = 'Easy'
body = '''
No need to understand PromQL for you intelligence teams.
'''
[[params.two.section]]
title = 'Expertise'
body = '''
Built by professionals for professionals
'''

[[params.cta.link]]
href = "#contact"
text = "Learn More!"
special = false

[params.cta]
enable = false

[[params.menu.main]]
url = '/'
title = "Home"

[params.contact]
enable = true
title = "Signup!"
body = "Sign up to stay informed"
email = "nospam@example.com"
